/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.calculatearea;

/**
 *
 * @author user
 */
public class CalculateArea extends javax.swing.JFrame {

    /**
     * Creates new form CalculateArea
     */
    public CalculateArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setBackground(new java.awt.Color(255, 0, 153));
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 255, 255));
        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(255, 153, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acres", "Square meters", "Square feet", "Square inches", "Ares", "Hectares" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setBackground(new java.awt.Color(153, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acres", "Square meters", "Square feet", "Square inches", "Ares", "Hectares" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calculate");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 0, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Area Calculator");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Select area options  to calculate:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("GROUP 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double num = Double.parseDouble(jTextField1.getText());
        if(jComboBox1.getSelectedItem().toString()== "Acres" && jComboBox2.getSelectedItem().toString()== "Square meters"){
        double result = num*4047;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Acres"&&jComboBox2.getSelectedItem().toString() == "Square feet"){
        double result = num*43560;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Acres"&&jComboBox2.getSelectedItem().toString() == "Square inches"){
        double result = num*6.273e+6;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Acres"&&jComboBox2.getSelectedItem().toString() == "Ares"){
        double result = num*40.469;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Acres"&&jComboBox2.getSelectedItem().toString() == "Hectares"){
        double result = num/2.471;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square meters"&&jComboBox2.getSelectedItem().toString() == "Acres"){
        double result = num/4047;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square meters"&&jComboBox2.getSelectedItem().toString() == "Square feet"){
        double result = num*10.764;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square meters"&&jComboBox2.getSelectedItem().toString() == "Square inches"){
        double result = num*1550;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square meters"&&jComboBox2.getSelectedItem().toString() == "Ares"){
        double result = num/100;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square meters"&&jComboBox2.getSelectedItem().toString() == "Hectares"){
        double result = num/10000;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square feet"&&jComboBox2.getSelectedItem().toString() == "Acres"){
        double result = num/43560;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square feet"&&jComboBox2.getSelectedItem().toString() == "Square meters"){
        double result = num/10.764;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square feet"&&jComboBox2.getSelectedItem().toString() == "Square inches"){
        double result = num*144;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square feet"&&jComboBox2.getSelectedItem().toString() == "Ares"){
        double result = num/1076;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square feet"&&jComboBox2.getSelectedItem().toString() == "Hectares"){
        double result = num/107600;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square inches"&&jComboBox2.getSelectedItem().toString() == "Acres"){
        double result = num/6.273e+6;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square inches"&&jComboBox2.getSelectedItem().toString() == "Square meters"){
        double result = num/1550;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square inches"&&jComboBox2.getSelectedItem().toString() == "Square feet"){
        double result = num/144;
        jTextField2.setText(result+"");
        }
           
        if(jComboBox1.getSelectedItem().toString() == "Square inches"&&jComboBox2.getSelectedItem().toString() == "Ares"){
        double result = num/155000;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square inches"&&jComboBox2.getSelectedItem().toString() == "Hectares"){
        double result = num/1.55e+7;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Ares"&&jComboBox2.getSelectedItem().toString() == "Acres"){
        double result = num*1076;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Ares"&&jComboBox2.getSelectedItem().toString() == "Square meters"){
        double result = num*100;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Ares"&&jComboBox2.getSelectedItem().toString() == "Square feet"){
        double result = num*1076;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Ares"&&jComboBox2.getSelectedItem().toString() == "Square inches"){
        double result = num*155000;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Ares"&&jComboBox2.getSelectedItem().toString() == "Hectares"){
        double result = num/100;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Hectares"&&jComboBox2.getSelectedItem().toString() == "Acres"){
        double result = num*2.71;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Hectares"&&jComboBox2.getSelectedItem().toString() == "Square meters"){
        double result = num*10000;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Hectares"&&jComboBox2.getSelectedItem().toString() == "Square feet"){
        double result = num*107600;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Hectares"&&jComboBox2.getSelectedItem().toString() == "Square inches"){
        double result = num*1.55e+7;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Hectares"&&jComboBox2.getSelectedItem().toString() == "Ares"){
        double result = num*100;
        jTextField2.setText(result+"");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
